server:
  port: 58080
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  config:
    activate:
      on-profile: default
  application:
    name: fiss
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 1000MB
      max-request-size: 1000MB

logging:
  level:
    root: info

geometry:
  srid: 3857

jwt:
  access-token-expired: ${JWT_ACCESS_TOKEN_EXPIRED}
  refresh-token-expired: ${JWT_REFRESH_TOKEN_EXPIRED}
  secret:
    key: ${JWT_SECRET_KEY}

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
  server:
    port: 8088
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"
      base-path: /actuator
  metrics:
    enable:
      all: true
  prometheus:
    metrics:
      export:
        enabled: true

info:
  app:
    name: fiss
    owner: pcn